Repository blakmetall/pmv, pull requests merged in 2021-04, with the labels that each got.

#22 Correción de columnas para los balances
  resources/views/property-management-transactions/partials/table.blade.php
Labels: enhancement

#29 Se refactorizo el codigo para separar 2 funcionalidades que compartia…
  app/Helpers/helpers.php
  public/assets/js/common-bundle-script.js
  public/assets/js/gull-script.js
  public/assets/public/css/public.css
  public/assets/public/js/public.js
  public/assets/styles/css/themes/palmera-vacations.min.css
  public/css/app.css
  public/css/vendor.css
  public/js/app.js
  public/js/scripts.js
  resources/js/scripts.js
  resources/js/scripts/initCheckAvailabilityProperty.js
  resources/js/scripts/initGetPmPropertySelectionEvent.js
Labels: to be merged

#30 Filter notes property by property selected
  app/Http/Controllers/PropertyNotesController.php
Labels: to be merged

#31 Se agrego la colección de imagenes que se crean en el controlador est…
  resources/views/property-images/index.blade.php
Labels: to be merged

#32 Add rental-agent rol permissions to add users
  app/Helpers/RoleHelper.php
Labels: to be merged

#37 remove sleeps field from properties and keep pax field
  app/Models/Property.php
  app/Validations/PropertiesValidations.php
  database/migrations/2021_04_17_000001_update_properties_table_remove_sleeps.php
  resources/lang/en.json
  resources/lang/es.json
  resources/views/properties/partials/form-fields.blade.php
  resources/views/public/pages/properties/property-booking.blade.php
Labels: merge review required
